export interface LoginRequest {
  email: string;
  password: string;
}

// Generated by https://quicktype.io

export interface LoginResponse {
  message?: string;
  id: number;
  name: string;
  lastName?: string;
  email: string;
}
